spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:socorro_ms_user_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:iUBW5IUsIUBiuBWI4U5Bç45ubX5I5WU4b5I4UlB5}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update